# Generated by Django 5.2.2 on 2025-07-07 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaSalida',
            fields=[
                ('idActaSalida', models.AutoField(primary_key=True, serialize=False)),
                ('codReq', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('idCaracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionCaracteristica', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('idComponente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComponente', models.CharField(max_length=100)),
                ('numeroSerie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcionComponente', models.CharField(choices=[('De Marca', 'de marca'), ('Compatible', 'compatible'), ('Otros', 'otros')], max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EquiposInformatico',
            fields=[
                ('idEquipoInformatico', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEquipoInformatico', models.CharField(max_length=100)),
                ('codigoPatrimonial', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('numeroSerie', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('observacionEquipo', models.CharField(max_length=400)),
                ('descripcionEquipo', models.CharField(choices=[('De Marca', 'de marca'), ('Compatible', 'compatible'), ('Otros', 'otros')], max_length=100)),
                ('añoGarantia', models.PositiveIntegerField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja')], default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('idEstablecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEstablecimiento', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('idFormato', models.AutoField(primary_key=True, serialize=False)),
                ('codigoFormato', models.CharField(max_length=100)),
                ('versionFormato', models.CharField(max_length=100)),
                ('fechaFormato', models.DateTimeField(auto_now_add=True)),
                ('estadoFormato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('idLote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fechaAdquisicion', models.DateField()),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('idTipoComponente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('idTipoEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteCaracteristica',
            fields=[
                ('idComponenteCaracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255)),
                ('idCaracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.caracteristicas')),
                ('idComponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.componentes')),
            ],
            options={
                'db_table': 'ComponenteCaracteristica',
            },
        ),
        migrations.AddField(
            model_name='componentes',
            name='idEquipoInformatico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soft_utes.equiposinformatico'),
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateTimeField(auto_now_add=True)),
                ('idActaSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.actasalida')),
                ('idEquipoInformatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.equiposinformatico')),
            ],
        ),
        migrations.AddField(
            model_name='actasalida',
            name='idEquipoInformatico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soft_utes.equiposinformatico'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idArea', models.AutoField(primary_key=True, serialize=False)),
                ('areaNombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
                ('idEstablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.establecimiento')),
            ],
        ),
        migrations.AddField(
            model_name='actasalida',
            name='idEstablecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.establecimiento'),
        ),
        migrations.AddField(
            model_name='actasalida',
            name='idFormato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.formato'),
        ),
        migrations.AddField(
            model_name='equiposinformatico',
            name='idLote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soft_utes.lote'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='idLote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soft_utes.lote'),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreModelo', models.CharField(max_length=100)),
                ('descripcionModelo', models.CharField(max_length=400)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='modelos/')),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.marca')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='idModelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.modelo'),
        ),
        migrations.AddField(
            model_name='equiposinformatico',
            name='idModelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soft_utes.modelo'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='idModelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.modelo'),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('idPersonal', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('Apellidos', models.CharField(max_length=100)),
                ('Nombres', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.cargo')),
                ('idEstablecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.establecimiento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actasalida',
            name='idPersonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.personal'),
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('idSubarea', models.AutoField(primary_key=True, serialize=False)),
                ('subareaNombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='ACTIVO', max_length=100)),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.area')),
            ],
        ),
        migrations.AddField(
            model_name='componentes',
            name='idTipoComponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.tipocomponente'),
        ),
        migrations.AddField(
            model_name='caracteristicas',
            name='idTipoComponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='soft_utes.tipocomponente'),
        ),
        migrations.AddField(
            model_name='equiposinformatico',
            name='idTipoEquipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_utes.tipoequipo'),
        ),
    ]
